# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
cairo=1.12.18=6
cycler=0.9.0=py27_0
fontconfig=2.11.1=5
freetype=2.5.5=0
gensim=0.12.2=np110py27_0
jupyter=1.0.0
libgfortran=1.0=0
libpng=1.6.17=0
libxml2=2.9.2=0
matplotlib=1.5.0=np110py27_0
numpy=1.10.2=py27_0
openblas=0.2.14=3
openssl=1.0.2d=0
pandas=0.17.1=np110py27_0
pip=7.1.2=py27_0
pixman=0.32.6=0
py2cairo=1.10.0=py27_2
pyparsing=2.0.3=py27_0
pyqt=4.11.4=py27_1
python=2.7.11=0
python-dateutil=2.4.2=py27_0
pytz=2015.7=py27_0
qt=4.8.7=1
readline=6.2=2
scipy=0.16.1=np110py27_0
scikit-learn=0.17
seaborn=0.6.0=np110py27_0
setuptools=19.1.1=py27_0
simplejson=3.8.0=py27_0
sip=4.16.9=py27_0
six=1.10.0=py27_0
sqlite=3.8.4.1=1
tk=8.5.18=0
wheel=0.26.0=py27_1
zlib=1.2.8=0
